/**
 * Username: nerdbook
 * Password: nerdbook1
**/

CREATE DATABASE nerdbook;

CREATE TABLE utente (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    cognome VARCHAR(128),
    datanascita DATE,
    email VARCHAR(128),
    password VARCHAR(128),
    frasepresntazione VARCHAR(128),
    urlFoto VARCHAR(128)
);

CREATE TABLE gruppo(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    imgGruppo VARCHAR(128),
);

CREATE TABLE post(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gruppoid INTEGER,
    autore INTEGER, --chi lo ha postato
    user INTEGER, --bacheca in cui è postato
    content VARCHAR(256),
    allegato VARCHAR(256),
    postType VARCHAR(32),
    FOREIGN KEY (autore) REFERENCES utente(id),
    FOREIGN KEY (gruppoid) REFERENCES gruppo(id),
    FOREIGN KEY (user) REFERENCES utente(id),
);

CREATE TABLE gruppiutente(
   id_utente INTEGER;
   id_gruppo INTEGER;
   FOREIGN KEY(id_utente) REFERENCES utente(id),
   FOREIGN KEY(id_gruppo) REFERENCES gruppo(id),
   PRIMARY KEY(id_utente, id_gruppo)
);

CREATE TABLE amicizia(
    id_utente1 INTEGER,
    id_utente2 INTEGER,
    FOREIGN KEY(id_utente1) REFERENCES utente(id),
    FOREIGN KEY(id_utente2) REFERENCES utente(id),
    PRIMARY KEY(id_utente, id_gruppo)
);