/**
 * Username: nerdbook    
 * Password: nerdbook1
**/

CREATE DATABASE nerdbook;

CREATE TABLE utente (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    cognome VARCHAR(128),
    datanascita DATE,
    email VARCHAR(128),
    password VARCHAR(128),
    frasepresentazione VARCHAR(128),
    urlFoto VARCHAR(128)
);

CREATE TABLE gruppo(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    imgGruppo VARCHAR(128)
);

CREATE TABLE post(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gruppoid INTEGER,
    autore INTEGER, --chi lo ha postato
    utente INTEGER, --bacheca in cui è postato
    content VARCHAR(256),
    allegato VARCHAR(256),
    postType VARCHAR(32),
    FOREIGN KEY (autore) REFERENCES utente(id),
    FOREIGN KEY (gruppoid) REFERENCES gruppo(id),
    FOREIGN KEY (utente) REFERENCES utente(id)
);

CREATE TABLE gruppiutente(
   id_utente INTEGER,
   id_gruppo INTEGER,
   FOREIGN KEY(id_utente) REFERENCES utente(id),
   FOREIGN KEY(id_gruppo) REFERENCES gruppo(id),
   PRIMARY KEY(id_utente, id_gruppo)
);

CREATE TABLE amicizia(
    id_utente1 INTEGER,
    id_utente2 INTEGER,
    FOREIGN KEY(id_utente1) REFERENCES utente(id),
    FOREIGN KEY(id_utente2) REFERENCES utente(id),
    PRIMARY KEY(id_utente, id_gruppo)
);


INSERT INTO UTENTE (id,nome,cognome,datanascita,email,password,frasepresentazione,urlfoto) values (default,'Monkey D.','Luffy','08/18/1996','monkeyd@gmail.com','123','','Assets/luffy1.jpg');
INSERT INTO UTENTE (id,nome,cognome,datanascita,email,password,frasepresentazione,urlfoto) values (default,'Fat','Cat','11/06/2000','fatcat@gmail.com','123','Sono affamato','Assets/gatto1.jpg');
INSERT INTO UTENTE (id,nome,cognome,datanascita,email,password,frasepresentazione,urlfoto) values (default,'Maestro','Muten','01/01/1930','maestro@gmail.com','123','Dove sono le ragazze?','Assets/genio1.jpg');

INSERT INTO POST (id,gruppoid,autore,utente,content,allegato,posttype) values (default,null,1,1,'Che fame!',null,'TEXT');
INSERT INTO POST (id,gruppoid,autore,utente,content,allegato,posttype) values (default,null,2,2,'il mio padrone che ci nutre!','Assets/download.jpg','IMAGE');
INSERT INTO POST (id,gruppoid,autore,utente,content,allegato,posttype) values (default,null,3,3,'Io e il mio amico in vacanza!','Assets/muten.png','LINK');


INSERT INTO GRUPPO (id,nome,imggruppo) values (default,'Mongolfieristi','Assets/mongolfiera.jpg');
INSERT INTO GRUPPO (id,nome,imggruppo) values (default,'Ritardatari','Assets/clock.png');

INSERT INTO GRUPPiUTENTE (id_utente,id_gruppo) values (1,2);
INSERT INTO GRUPPiUTENTE (id_utente,id_gruppo) values (3,1);
INSERT INTO GRUPPiUTENTE (id_utente,id_gruppo) values (2,1);
INSERT INTO GRUPPiUTENTE (id_utente,id_gruppo) values (2,2);



